### ISSUE TITLE
OptionButton dropdown doesn't move if the window moves

### ISSUE THREAD

**Issue by exp111** [space-wizards/RobustToolbox#1339] opened 2020-10-16 13:10 UTC
Steps:
1. Open a control with a OptionButton
2. Open the dropdown
3. Move the window (which closes the dropdown)
4. Open the dropdown again
**Expected:**
Dropdown shows at the new position
**Actual:**
![grafik](https://user-images.githubusercontent.com/17885980/96262075-92be9380-0fc1-11eb-9616-4fb6839dd0a7.png)

**Comment by Acruid** [comment] 2021-03-31 03:02
Cannot reproduce, assumed to be fixed with the UI layout rework.

**Closed as completed by Acruid** 2021-03-31 03:02 UTC
Labels: T: Bugfix, A: UI
