### ISSUE TITLE
Abrupt client disconnect memory leaks server.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#558] opened 2018-04-13 13:10 UTC
The server doesn't time out clients on debug builds, to prevent disconnects while debugging (useful).

Problem is that if the client crashes and never tells the server it's disconnected, the server will keep piling on entity state deltas for the client, causing it to basically memory leak slowly. Only fix is a restart.

**Comment by Acruid** [comment] 2018-04-13 18:30
This is not really a "leak", as the memory is not being lost. The client stops acknowledging the game state deltas, so the server has to keep a history of every state that is sent since the last ack'd state. The main problem is the client is not timing out (because debug), and there is no coded limit to how much state history the server holds for a client since the last ack.

The 'proper' solution is to set a limit of how large the backlog of states can get. This way if the client stops ack'ing states for a few seconds, the server will just stop creating delta states and flush the old ones. If the client ever starts responding again the server can just start fresh with a full state and generate deltas from there. This solution will also help prevent abuse where client stays connected, but does not ack states.

A short term work-around is to use the server `kick` command on the timed out client.

**Comment by PJB3005** [comment] 2018-05-13 09:41
This still happens even after #586, though this time I suspect it's just net messages piling up and Lidgren waiting for them to be acked.

It's much less significant though.

**Comment by Acruid** [comment] 2018-08-06 19:40
It needs to be verified that the client cannot DOS the server by not sending state ACKs. See the second part of my response above for a way to resolve this issue.

**Comment by captkirk88** [comment] 2018-08-07 01:03
Couldn't you also solve that with a good keep alive message every 5 seconds (as a example)?

If there is no keep alive, disconnect the client since they are ded.

I think you guys are using Lidgren still, if so, it has that ability you just have to enable it.

**Comment by Acruid** [comment] 2018-08-07 01:25
The problem is that the client stops acknowledging the game states every tick, so the server has to store every state for every tick between the last ack'd state and the current tick. Currently there is no coded limit to how large the buffer can be, so the client can DOS the server by not ack'ing states and let millions of states pile up. This is unrelated to lidgren's keep alive messages, which are disabled atm for debug purposes, but will be enabled for releases.

**Comment by captkirk88** [comment] 2018-08-07 01:58
I see your point.  I was going with the assumption that if the client was disconnected and you were disposing of the buffer related to that client when the disconnect event was fired (as a result of not receiving a keep alive), then there would be no buffer to worry about because it was disposed of when the server discovered the client was inactive.

**Comment by PJB3005** [comment] 2018-08-09 16:07
I'm gonna drop the priority because we're not all too worried about DOS attacks yet. We're not going for stability yet.

**Comment by Acruid** [comment] 2019-05-23 19:09
Currently in a debug build, the server will not time out a client, which is required for pausing the client when debugging. The downside to this is that an improperly disconnected client will leave its zombie session on the server.

Since https://github.com/space-wizards/RobustToolbox/pull/586 the server has not stored game states. They are created on-demand. Later PRs improved this feature, but regardless a client that stops acking states does not cause a giant pileup of states on the server anymore.

Currently in release builds (what every public server should be running), this is a non-issue because an unresponsive client will time out and be forcefully disconnected by Lidgren, and their session will be cleaned up normally.

Pretty much all of the information is outdated in this issue, and there is nothing really left to fix, so i'm closing this issue. If someone has a specific question ask us in the Discord server.

**Closed as completed by Acruid** 2019-05-23 19:09 UTC
Labels: T: Bugfix, Priority: 3-Not Required, A: Game Networking
