### ISSUE TITLE
WorldBounds rounding issues

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#3236] opened 2022-09-06 04:20 UTC
Explosion Overlays don't extend across the entire viewport.

**Comment by ElectroJr** [comment] 2022-09-06 05:12
The issue is just that explosions check if the tile centre lies inside of the bounds, not if any part of the tile does, leading to visual pop-in when moving around. So this isn't an engine / general world bounds issue.

The overlay should get fixed by space-wizards/space-station-14/pull/11074, which just enlarges the bounds a bit.

**Closed as completed** 2022-09-06 05:27 UTC
Labels: T: Bugfix, Priority: 2-Important, D2: Medium
