### ISSUE TITLE
Hitting the main menu options button while connecting crashes the client.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#740] opened 2019-02-22 12:28 UTC
With "while connecting" I mean "in the window of time where the main menu is still up but the connection handshake has succeeded and the client is loading the map and such".

```
Unhandled Exception:
System.InvalidOperationException: Window is not a child of the window root! You need to call AddToScreen first!
  at SS14.Client.UserInterface.CustomControls.SS14Window.OpenCentered () [0x00055] in /ssdhome/pj/Projects/space-station-14-content/engine/SS14.Client/UserInterface/CustomControls/SS14Window.cs:348 
  at SS14.Client.State.States.MainScreen.OptionsButtonPressed (SS14.Client.UserInterface.Controls.BaseButton+ButtonEventArgs args) [0x00001] in /ssdhome/pj/Projects/space-station-14-content/engine/SS14.Client/State/States/MainMenu.cs:81 
  at SS14.Client.UserInterface.Controls.BaseButton.MouseUp (SS14.Client.UserInterface.GUIMouseButtonEventArgs args) [0x00079] in /ssdhome/pj/Projects/space-station-14-content/engine/SS14.Client/UserInterface/Controls/BaseButton.cs:228 
  at SS14.Client.UserInterface.UserInterfaceManager+<>c.<MouseUp>b__56_0 (SS14.Client.UserInterface.Control c, SS14.Client.UserInterface.GUIMouseButtonEventArgs ev) [0x00000] in /ssdhome/pj/Projects/space-station-14-content/engine/SS14.Client/UserInterface/UserInterfaceManager.cs:180 
  at SS14.Client.UserInterface.UserInterfaceManager._doMouseGuiInput[T] (SS14.Client.UserInterface.Control control, T guiEvent, System.Action`2[T1,T2] action) [0x00015] in /ssdhome/pj/Projects/space-station-14-content/engine/SS14.Client/UserInterface/UserInterfaceManager.cs:440 
  at SS14.Client.UserInterface.UserInterfaceManager.MouseUp (SS14.Client.Input.MouseButtonEventArgs args) [0x00061] in /ssdhome/pj/Projects/space-station-14-content/engine/SS14.Client/UserInterface/UserInterfaceManager.cs:180 
  at SS14.Client.GameController.MouseUp (SS14.Client.Input.MouseButtonEventArgs mouseButtonEventArgs) [0x0001c] in /ssdhome/pj/Projects/space-station-14-content/engine/SS14.Client/GameController/GameController.Input.cs:70 
  at SS14.Client.Graphics.Clyde.Clyde.<_initWindow>b__44_5 (System.Object sender, OpenTK.Input.MouseButtonEventArgs eventArgs) [0x00008] in /ssdhome/pj/Projects/space-station-14-content/engine/SS14.Client/Graphics/Clyde/Clyde.cs:165 
  at (wrapper delegate-invoke) System.EventHandler`1[OpenTK.Input.MouseButtonEventArgs].invoke_void_object_TEventArgs(object,OpenTK.Input.MouseButtonEventArgs)
  at OpenTK.NativeWindow.OnMouseUp (OpenTK.Input.MouseButtonEventArgs e) [0x00000] in /home/jarl/Programming/opentk-3.0/src/OpenTK/NativeWindow.cs:769 
  at OpenTK.NativeWindow.OnMouseUpInternal (System.Object sender, OpenTK.Input.MouseButtonEventArgs e) [0x00000] in /home/jarl/Programming/opentk-3.0/src/OpenTK/NativeWindow.cs:896 
  at (wrapper delegate-invoke) System.EventHandler`1[OpenTK.Input.MouseButtonEventArgs].invoke_void_object_TEventArgs(object,OpenTK.Input.MouseButtonEventArgs)
  at OpenTK.Platform.NativeWindowBase.OnMouseUp (OpenTK.Input.MouseButton button) [0x0002e] in /home/jarl/Programming/opentk-3.0/src/OpenTK/Platform/NativeWindowBase.cs:255 
  at OpenTK.Platform.SDL2.Sdl2NativeWindow.ProcessMouseButtonEvent (OpenTK.Platform.SDL2.Sdl2NativeWindow window, OpenTK.Platform.SDL2.MouseButtonEvent ev) [0x00040] in /home/jarl/Programming/opentk-3.0/src/OpenTK/Platform/SDL2/Sdl2NativeWindow.cs:240 
  at OpenTK.Platform.SDL2.Sdl2NativeWindow.ProcessEvent (OpenTK.Platform.SDL2.Event& ev) [0x00115] in /home/jarl/Programming/opentk-3.0/src/OpenTK/Platform/SDL2/Sdl2NativeWindow.cs:183 
  at OpenTK.Platform.SDL2.Sdl2NativeWindow.ProcessEvents () [0x00022] in /home/jarl/Programming/opentk-3.0/src/OpenTK/Platform/SDL2/Sdl2NativeWindow.cs:582 
  at OpenTK.NativeWindow.ProcessEvents (System.Boolean retainEvents) [0x00035] in /home/jarl/Programming/opentk-3.0/src/OpenTK/NativeWindow.cs:868 
  at OpenTK.NativeWindow.ProcessEvents () [0x00000] in /home/jarl/Programming/opentk-3.0/src/OpenTK/NativeWindow.cs:169 
  at SS14.Client.Graphics.Clyde.Clyde.ProcessInput (SS14.Client.FrameEventArgs frameEventArgs) [0x00001] in /ssdhome/pj/Projects/space-station-14-content/engine/SS14.Client/Graphics/Clyde/Clyde.cs:95 
  at SS14.Client.GameController.<MainLoop>b__55_2 (System.Object sender, SS14.Shared.Timing.FrameEventArgs args) [0x00000] in /ssdhome/pj/Projects/space-station-14-content/engine/SS14.Client/GameController/GameController.Standalone.cs:70 
  at SS14.Shared.Timing.GameLoop.Run () [0x0012e] in /ssdhome/pj/Projects/space-station-14-content/engine/SS14.Shared/Timing/GameLoop.cs:94 
  at SS14.Client.GameController.MainLoop () [0x00092] in /ssdhome/pj/Projects/space-station-14-content/engine/SS14.Client/GameController/GameController.Standalone.cs:79 
  at SS14.Client.GameController.Main () [0x00042] in /ssdhome/pj/Projects/space-station-14-content/engine/SS14.Client/GameController/GameController.Standalone.cs:38 
```

**Comment by Acruid** [comment] 2019-05-16 20:07
I cannot reproduce this. Removing Godot and changing the handshake to async prob fixed this. I'm closing this, if this is still an issue free to reopen.

**Closed as completed by Acruid** 2019-05-16 20:07 UTC
Labels: T: Bugfix, Priority: 3-Not Required
