### ISSUE TITLE
ToMapPos should throw if the coordinates are invalid

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1854] opened 2021-07-07 11:17 UTC
Currently it resolves to 0,0 on the nullspace grid so it might be feeding you garbage and you don't know it.

Realistically you'll need to add it as an exception then run tests / playtest in-game because some stuff will very likely break.

**Comment by Acruid** [comment] 2021-11-29 07:27
IsValid is designed to handle NaN positions. Sending mover ents to nullspace is a core piece of the current PVS system, so this is a duplicate of https://github.com/space-wizards/RobustToolbox/issues/1210.

**Closed as completed by Acruid** 2021-11-29 07:27 UTC
Labels: T: Bugfix, D1: High
