### ISSUE TITLE
Buttons and other controls can become "stuck" due to control focus issues

### ISSUE THREAD

**Issue by chairbender** [space-wizards/RobustToolbox#1468] opened 2020-12-24 06:55 UTC
Use the new capabilities provided in #1467 to fix issues affecting controls w.r.t. focus stealing.

For example, on buttons, you can press LMB, drag off to a different control, press RMB, then release LMB. The original button will be stuck in the "pressed" state. It should instead reset to unpressed when you click RMB during the drag.

We should also go through Content and check for any related issues there in Content-specific controls, and fix them as part of this work.

**Comment by PaulRitter** [comment] 2021-01-20 20:06
is this fixed?

**Comment by chairbender** [comment] 2021-01-20 22:31
No.

**Comment by Acruid** [comment] 2021-12-10 20:05
I cannot reproduce this on the client main menu or ingame admin menu, so I am going to close this as fixed. If there are specific UIs that are broken in content, then an issue needs to be opened in content to fix them. If there is an actual bug with the UI system that can be reproduced, open another issue for that bug.

**Closed as completed by Acruid** 2021-12-10 20:05 UTC
Labels: T: Bugfix, A: UI

**Comment by ShadowCommander** [comment] 2021-12-10 20:45
Fixed by #1978
